- name: Utils | Including playbook for RedHat operating systems.
  include: RedHat.yml
  when: ansible_os_family == "RedHat"

- name: Utils | Including playbook for Debian operating systems.
  include: Debian.yml
  when: ansible_os_family == "Debian"
